/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package day01multitempconv;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;


/**
 *
 * @author YingLuo
 */
public class Day01MultiTempConv extends javax.swing.JFrame {

    /**
     * Creates new form Day01Task02
     */
    public Day01MultiTempConv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputButtonGroup = new javax.swing.ButtonGroup();
        outputButtonGroup = new javax.swing.ButtonGroup();
        lblInput = new javax.swing.JLabel();
        tfInput = new javax.swing.JTextField();
        lblInputScale = new javax.swing.JLabel();
        btInputCelsius = new javax.swing.JRadioButton();
        btInputFah = new javax.swing.JRadioButton();
        btInputKelvin = new javax.swing.JRadioButton();
        lblOutputScale = new javax.swing.JLabel();
        btOutputCelsius = new javax.swing.JRadioButton();
        btOutputFah = new javax.swing.JRadioButton();
        btOutputKelvin = new javax.swing.JRadioButton();
        lblOutput = new javax.swing.JLabel();
        tfOutput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblInput.setText("Input");

        tfInput.setText("100");
        tfInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputActionPerformed(evt);
            }
        });

        lblInputScale.setText("Input Scale");

        inputButtonGroup.add(btInputCelsius);
        btInputCelsius.setText("Celsius");
        btInputCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInputCelsiusActionPerformed(evt);
            }
        });

        inputButtonGroup.add(btInputFah);
        btInputFah.setText("Fahrenheit");
        btInputFah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInputFahActionPerformed(evt);
            }
        });

        inputButtonGroup.add(btInputKelvin);
        btInputKelvin.setText("Kelvin");
        btInputKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInputKelvinActionPerformed(evt);
            }
        });

        lblOutputScale.setText("Output Scale");

        outputButtonGroup.add(btOutputCelsius);
        btOutputCelsius.setText("Celsius");
        btOutputCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOutputCelsiusActionPerformed(evt);
            }
        });

        outputButtonGroup.add(btOutputFah);
        btOutputFah.setText("Fahrenheit");
        btOutputFah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOutputFahActionPerformed(evt);
            }
        });

        outputButtonGroup.add(btOutputKelvin);
        btOutputKelvin.setText("Kelvin");
        btOutputKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOutputKelvinActionPerformed(evt);
            }
        });

        lblOutput.setText("Output");

        tfOutput.setText("212 °F");
        tfOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOutputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblInput)
                        .addGap(18, 18, 18)
                        .addComponent(tfInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInputScale)
                            .addComponent(btInputCelsius)
                            .addComponent(btInputFah)
                            .addComponent(btInputKelvin))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btOutputKelvin)
                            .addComponent(btOutputFah)
                            .addComponent(btOutputCelsius)
                            .addComponent(lblOutputScale)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblOutput)
                        .addGap(18, 18, 18)
                        .addComponent(tfOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInput)
                    .addComponent(tfInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInputScale)
                    .addComponent(lblOutputScale))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInputCelsius)
                    .addComponent(btOutputCelsius))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInputFah)
                    .addComponent(btOutputFah))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInputKelvin)
                    .addComponent(btOutputKelvin))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOutput)
                    .addComponent(tfOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputActionPerformed
    
    private void btInputKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInputKelvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btInputKelvinActionPerformed

    private void btInputCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInputCelsiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btInputCelsiusActionPerformed

    private void btInputFahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInputFahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btInputFahActionPerformed

    private void tfOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOutputActionPerformed
        // TODO add your handling code here:
        
        tfOutput.setEditable(false);
        
        try{
            Double inputValue = Double.parseDouble(tfInput.getText());
            Double outputValue;
            String result;
                    
            if(btInputKelvin.isSelected() && btOutputCelsius.isSelected()){
                outputValue = inputValue - 273.15;
                
            }else if(btInputKelvin.isSelected() && btOutputFah.isSelected()){
                outputValue = ( inputValue - 273.15 ) * 9 / 5 + 32;
                
            }else if(btInputFah.isSelected() && btOutputCelsius.isSelected()){
                outputValue = ( inputValue - 32) * 5 / 9;
                
            }else if(btInputFah.isSelected() && btOutputKelvin.isSelected()){
                outputValue = ( inputValue - 32) * 5 / 9 + 273.15;
                
            }else if(btInputCelsius.isSelected() && btOutputKelvin.isSelected()){
                outputValue = inputValue + 273.15;
                
            }else if(btInputCelsius.isSelected() && btOutputFah.isSelected()){
                outputValue = inputValue * 9 / 5 + 32;
                
            }else{
                JOptionPane.showMessageDialog(null, "Please choose different Input and Output temperatures");
                outputValue = inputValue;
                
            }
            
            result = String.format("%.2f °F", outputValue);
            tfOutput.setText(result);
                
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e, "Exception", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tfOutputActionPerformed

    private void btOutputCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOutputCelsiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btOutputCelsiusActionPerformed

    private void btOutputFahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOutputFahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btOutputFahActionPerformed

    private void btOutputKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOutputKelvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btOutputKelvinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day01MultiTempConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day01MultiTempConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day01MultiTempConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day01MultiTempConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day01MultiTempConv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btInputCelsius;
    private javax.swing.JRadioButton btInputFah;
    private javax.swing.JRadioButton btInputKelvin;
    private javax.swing.JRadioButton btOutputCelsius;
    private javax.swing.JRadioButton btOutputFah;
    private javax.swing.JRadioButton btOutputKelvin;
    private javax.swing.ButtonGroup inputButtonGroup;
    private javax.swing.JLabel lblInput;
    private javax.swing.JLabel lblInputScale;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblOutputScale;
    private javax.swing.ButtonGroup outputButtonGroup;
    private javax.swing.JTextField tfInput;
    private javax.swing.JTextField tfOutput;
    // End of variables declaration//GEN-END:variables
}
