/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day01icecreamcalc;

import javax.swing.JOptionPane;

/**
 *
 * @author YingLuo
 */
public class Day01IceCreamCalc_Teacher extends javax.swing.JFrame {

    /**
     * Creates new form Day01IceCreamCalc
     */
    public Day01IceCreamCalc_Teacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        pnlFlavour = new javax.swing.JPanel();
        rdbtVanilla = new javax.swing.JRadioButton();
        rdbtStrawberry = new javax.swing.JRadioButton();
        rdbtChocolate = new javax.swing.JRadioButton();
        pnlTopping = new javax.swing.JPanel();
        ckbSprinkle = new javax.swing.JCheckBox();
        ckbPeanuts = new javax.swing.JCheckBox();
        ckbFudge = new javax.swing.JCheckBox();
        btCalculate = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        tfSubtotal = new javax.swing.JTextField();
        lblSubtotal = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        tfTax = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arsenio's Ice Cream");
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lblTitle.setText("Arsenio's Ice Cream");

        pnlFlavour.setBorder(javax.swing.BorderFactory.createTitledBorder("Flavours"));

        buttonGroup.add(rdbtVanilla);
        rdbtVanilla.setText("Vanilla $1.00");
        rdbtVanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtVanillaActionPerformed(evt);
            }
        });

        buttonGroup.add(rdbtStrawberry);
        rdbtStrawberry.setText("Strawberry $1.50");
        rdbtStrawberry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtStrawberryActionPerformed(evt);
            }
        });

        buttonGroup.add(rdbtChocolate);
        rdbtChocolate.setText("Chocolate $2.00");
        rdbtChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtChocolateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFlavourLayout = new javax.swing.GroupLayout(pnlFlavour);
        pnlFlavour.setLayout(pnlFlavourLayout);
        pnlFlavourLayout.setHorizontalGroup(
            pnlFlavourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFlavourLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFlavourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtStrawberry)
                    .addComponent(rdbtChocolate)
                    .addComponent(rdbtVanilla))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFlavourLayout.setVerticalGroup(
            pnlFlavourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFlavourLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(rdbtVanilla)
                .addGap(18, 18, 18)
                .addComponent(rdbtStrawberry)
                .addGap(18, 18, 18)
                .addComponent(rdbtChocolate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTopping.setBorder(javax.swing.BorderFactory.createTitledBorder("Toppings"));

        ckbSprinkle.setText("Sprinkles $.25");
        ckbSprinkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbSprinkleActionPerformed(evt);
            }
        });

        ckbPeanuts.setText("Peanuts $.50");
        ckbPeanuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbPeanutsActionPerformed(evt);
            }
        });

        ckbFudge.setText("Fudge $.75");
        ckbFudge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbFudgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlToppingLayout = new javax.swing.GroupLayout(pnlTopping);
        pnlTopping.setLayout(pnlToppingLayout);
        pnlToppingLayout.setHorizontalGroup(
            pnlToppingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToppingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlToppingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbSprinkle)
                    .addComponent(ckbPeanuts)
                    .addComponent(ckbFudge))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlToppingLayout.setVerticalGroup(
            pnlToppingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToppingLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ckbSprinkle)
                .addGap(18, 18, 18)
                .addComponent(ckbPeanuts)
                .addGap(18, 18, 18)
                .addComponent(ckbFudge)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btCalculate.setText("Calculate");
        btCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalculateActionPerformed(evt);
            }
        });

        btReset.setText("Reset Form");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        tfSubtotal.setText("0");
        tfSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSubtotalActionPerformed(evt);
            }
        });

        lblSubtotal.setText("Subtotal");

        lblTax.setText("Tax");

        tfTax.setText("0");
        tfTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTaxActionPerformed(evt);
            }
        });

        lblTotal.setText("Total");

        tfTotal.setText("0");
        tfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCalculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btReset)
                        .addGap(32, 32, 32)
                        .addComponent(btExit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlFlavour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(pnlTopping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblTitle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtotal)
                    .addComponent(lblTax)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfSubtotal)
                        .addComponent(tfTax, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblTitle)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlFlavour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTopping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCalculate)
                            .addComponent(btReset)
                            .addComponent(btExit)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubtotal)
                            .addComponent(tfSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTax)
                            .addComponent(tfTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    final Double SALES_TAX = 0.15;
    
    private void rdbtVanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtVanillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtVanillaActionPerformed

    private void btCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalculateActionPerformed
        // TODO add your handling code here:
    
        double subTotal = 0;
        
        if(rdbtChocolate.isSelected()){
            subTotal += 2.0;
        }else if(rdbtStrawberry.isSelected()){
            subTotal += 1.5;
        }else if(rdbtVanilla.isSelected()){
            subTotal += 1.00;
        }else{
            JOptionPane.showMessageDialog(null, "Please choose at least one flavour");
        }
        
        if(ckbSprinkle.isSelected()){
            subTotal += 0.25;
        }
        if(ckbPeanuts.isSelected()){
            subTotal += 0.5;
        }
        if(ckbFudge.isSelected()){
            subTotal += 0.75;
        }
        
        double tax = subTotal * SALES_TAX;
        double total = subTotal + tax;

        tfSubtotal.setText(String.format("%.2f", subTotal));
        tfTax.setText(String.format("%.2f", tax));
        tfTotal.setText(String.format("%.2f", total));

        
    }//GEN-LAST:event_btCalculateActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:       
        buttonGroup.clearSelection();
        ckbSprinkle.setSelected(false);
        ckbPeanuts.setSelected(false);
        ckbFudge.setSelected(false);
        tfSubtotal.setText("");
        tfTax.setText("");
        tfTotal.setText("");
    }//GEN-LAST:event_btResetActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
        setVisible(false); 
        dispose();
    }//GEN-LAST:event_btExitActionPerformed

    private void rdbtStrawberryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtStrawberryActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rdbtStrawberryActionPerformed

    private void rdbtChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtChocolateActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rdbtChocolateActionPerformed

    private void ckbSprinkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbSprinkleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbSprinkleActionPerformed

    private void ckbPeanutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbPeanutsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbPeanutsActionPerformed

    private void ckbFudgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbFudgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbFudgeActionPerformed

    private void tfTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTaxActionPerformed
        // TODO add your handling code here:
        tfTax.setEditable(false);
        tfTax.setEnabled(false);
    }//GEN-LAST:event_tfTaxActionPerformed

    private void tfSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSubtotalActionPerformed
        // TODO add your handling code here:
        tfSubtotal.setEditable(false);
        tfSubtotal.setEnabled(false);
    }//GEN-LAST:event_tfSubtotalActionPerformed

    private void tfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalActionPerformed
        // TODO add your handling code here:
        tfTotal.setEditable(false);
        tfTotal.setEnabled(false);
    }//GEN-LAST:event_tfTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day01IceCreamCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day01IceCreamCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day01IceCreamCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day01IceCreamCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day01IceCreamCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalculate;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btReset;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JCheckBox ckbFudge;
    private javax.swing.JCheckBox ckbPeanuts;
    private javax.swing.JCheckBox ckbSprinkle;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlFlavour;
    private javax.swing.JPanel pnlTopping;
    private javax.swing.JRadioButton rdbtChocolate;
    private javax.swing.JRadioButton rdbtStrawberry;
    private javax.swing.JRadioButton rdbtVanilla;
    private javax.swing.JTextField tfSubtotal;
    private javax.swing.JTextField tfTax;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
