/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day07birthdays;

/**
 *
 * @author YingLuo
 */
public class Day07Birthdays extends javax.swing.JFrame {

    /**
     * Creates new form Day07Birthdays
     */
    public Day07Birthdays() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgAddEdit = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dlgAddEdit_tfName = new javax.swing.JTextField();
        dlgAddEdit_btCancel = new javax.swing.JButton();
        dlgAddEdit_btAddUpdate = new javax.swing.JButton();
        dlgStatistic = new javax.swing.JDialog();
        lblStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstBirthdays = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miExport = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        rbmiSortName = new javax.swing.JRadioButtonMenuItem();
        rbmiSoryDaysTill = new javax.swing.JRadioButtonMenuItem();
        rbmiSortDaysTill = new javax.swing.JRadioButtonMenuItem();
        mnAdd = new javax.swing.JMenu();
        mnStatistic = new javax.swing.JMenu();

        jLabel1.setText("Name");

        jLabel2.setText("Birthday");

        dlgAddEdit_btCancel.setText("Cancel");

        dlgAddEdit_btAddUpdate.setText("Add");

        javax.swing.GroupLayout dlgAddEditLayout = new javax.swing.GroupLayout(dlgAddEdit.getContentPane());
        dlgAddEdit.getContentPane().setLayout(dlgAddEditLayout);
        dlgAddEditLayout.setHorizontalGroup(
            dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddEditLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dlgAddEditLayout.createSequentialGroup()
                        .addComponent(dlgAddEdit_btCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dlgAddEdit_btAddUpdate))
                    .addGroup(dlgAddEditLayout.createSequentialGroup()
                        .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addComponent(dlgAddEdit_tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        dlgAddEditLayout.setVerticalGroup(
            dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddEditLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dlgAddEdit_tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlgAddEdit_btCancel)
                    .addComponent(dlgAddEdit_btAddUpdate))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgStatisticLayout = new javax.swing.GroupLayout(dlgStatistic.getContentPane());
        dlgStatistic.getContentPane().setLayout(dlgStatisticLayout);
        dlgStatisticLayout.setHorizontalGroup(
            dlgStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dlgStatisticLayout.setVerticalGroup(
            dlgStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Birthdays");
        setResizable(false);

        lblStatus.setText("? days shown, ? birthday upcoming in next 7 days");
        getContentPane().add(lblStatus, java.awt.BorderLayout.PAGE_END);

        lstBirthdays.setModel(listModelBirthday);
        lstBirthdays.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstBirthdays);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        miExport.setText("Export to .csv...");
        jMenu1.add(miExport);

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        jMenu1.add(miExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sort By");

        rbmiSortName.setSelected(true);
        rbmiSortName.setText("Name");
        rbmiSortName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmiSortNameActionPerformed(evt);
            }
        });
        jMenu2.add(rbmiSortName);

        rbmiSoryDaysTill.setSelected(true);
        rbmiSoryDaysTill.setText("BirthDay");
        jMenu2.add(rbmiSoryDaysTill);

        rbmiSortDaysTill.setSelected(true);
        rbmiSortDaysTill.setText("Days Till Birthday");
        jMenu2.add(rbmiSortDaysTill);

        jMenuBar1.add(jMenu2);

        mnAdd.setText("Add");
        jMenuBar1.add(mnAdd);

        mnStatistic.setText("Statistics");
        jMenuBar1.add(mnStatistic);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbmiSortNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiSortNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbmiSortNameActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day07Birthdays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day07Birthdays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day07Birthdays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day07Birthdays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day07Birthdays().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dlgAddEdit;
    private javax.swing.JButton dlgAddEdit_btAddUpdate;
    private javax.swing.JButton dlgAddEdit_btCancel;
    private javax.swing.JTextField dlgAddEdit_tfName;
    private javax.swing.JDialog dlgStatistic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JList<Birthday> lstBirthdays;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miExport;
    private javax.swing.JMenu mnAdd;
    private javax.swing.JMenu mnStatistic;
    private javax.swing.JRadioButtonMenuItem rbmiSortDaysTill;
    private javax.swing.JRadioButtonMenuItem rbmiSortName;
    private javax.swing.JRadioButtonMenuItem rbmiSoryDaysTill;
    // End of variables declaration//GEN-END:variables
}
