/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day07birthdays;

import javax.swing.DefaultListModel;

/**
 *
 * @author YingLuo
 */
public class Day07Birthdays extends javax.swing.JFrame {

    /**
     * Creates new form Day07Birthdays
     */
    
    //System.out.println(System.getProperty("java.class.path"));
    
    DefaultListModel listModelBirthday = new DefaultListModel();
            
    public Day07Birthdays() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgAddEdit = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dlgAddEdit_tfName = new javax.swing.JTextField();
        dlgAddEdit_btCancel = new javax.swing.JButton();
        dlgAddEdit_btAddUpdate = new javax.swing.JButton();
        dlgStatistic = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dlgStatistic_tfTotalFriends = new javax.swing.JTextField();
        dlgStatistic_tfComingBirthdays = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dlgStatistic_lstBirthday = new javax.swing.JList<>();
        dlgStatistic_btDismiss = new javax.swing.JButton();
        fileChooser = new javax.swing.JFileChooser();
        lblStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstBirthdays = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miExport = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        rbmiSortName = new javax.swing.JRadioButtonMenuItem();
        rbmiSoryDaysTill = new javax.swing.JRadioButtonMenuItem();
        rbmiSortDaysTill = new javax.swing.JRadioButtonMenuItem();
        mnAdd = new javax.swing.JMenu();
        mnStatistic = new javax.swing.JMenu();

        dlgAddEdit.setResizable(false);

        jLabel1.setText("Name");

        jLabel2.setText("Birthday");

        dlgAddEdit_btCancel.setText("Cancel");

        dlgAddEdit_btAddUpdate.setText("Add");

        javax.swing.GroupLayout dlgAddEditLayout = new javax.swing.GroupLayout(dlgAddEdit.getContentPane());
        dlgAddEdit.getContentPane().setLayout(dlgAddEditLayout);
        dlgAddEditLayout.setHorizontalGroup(
            dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddEditLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dlgAddEditLayout.createSequentialGroup()
                        .addComponent(dlgAddEdit_btCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dlgAddEdit_btAddUpdate))
                    .addGroup(dlgAddEditLayout.createSequentialGroup()
                        .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addComponent(dlgAddEdit_tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        dlgAddEditLayout.setVerticalGroup(
            dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddEditLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dlgAddEdit_tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlgAddEdit_btCancel)
                    .addComponent(dlgAddEdit_btAddUpdate))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        dlgStatistic.setResizable(false);

        jLabel3.setText("Total No. of Friends");

        jLabel4.setText("Birthdays coming in 7 days");

        dlgStatistic_tfComingBirthdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgStatistic_tfComingBirthdaysActionPerformed(evt);
            }
        });

        jLabel5.setText("Birthday per Month");

        dlgStatistic_lstBirthday.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(dlgStatistic_lstBirthday);

        dlgStatistic_btDismiss.setText("Dismiss");

        javax.swing.GroupLayout dlgStatisticLayout = new javax.swing.GroupLayout(dlgStatistic.getContentPane());
        dlgStatistic.getContentPane().setLayout(dlgStatisticLayout);
        dlgStatisticLayout.setHorizontalGroup(
            dlgStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgStatisticLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(dlgStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dlgStatisticLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(178, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dlgStatisticLayout.createSequentialGroup()
                        .addGroup(dlgStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(dlgStatisticLayout.createSequentialGroup()
                                .addGroup(dlgStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(dlgStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dlgStatistic_tfComingBirthdays)
                                    .addComponent(dlgStatistic_tfTotalFriends)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(dlgStatisticLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(dlgStatistic_btDismiss)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dlgStatisticLayout.setVerticalGroup(
            dlgStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgStatisticLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(dlgStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dlgStatistic_tfTotalFriends, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(dlgStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dlgStatistic_tfComingBirthdays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dlgStatistic_btDismiss)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Birthdays");
        setMinimumSize(new java.awt.Dimension(300, 200));
        setResizable(false);

        lblStatus.setText("? days shown, ? birthday upcoming in next 7 days");
        getContentPane().add(lblStatus, java.awt.BorderLayout.PAGE_END);

        lstBirthdays.setModel(listModelBirthday);
        lstBirthdays.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstBirthdays);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        miExport.setText("Export to .csv...");
        jMenu1.add(miExport);

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        jMenu1.add(miExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sort By");

        rbmiSortName.setSelected(true);
        rbmiSortName.setText("Name");
        rbmiSortName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmiSortNameActionPerformed(evt);
            }
        });
        jMenu2.add(rbmiSortName);

        rbmiSoryDaysTill.setSelected(true);
        rbmiSoryDaysTill.setText("BirthDay");
        jMenu2.add(rbmiSoryDaysTill);

        rbmiSortDaysTill.setSelected(true);
        rbmiSortDaysTill.setText("Days Till Birthday");
        jMenu2.add(rbmiSortDaysTill);

        jMenuBar1.add(jMenu2);

        mnAdd.setText("Add");
        mnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnAddMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnAdd);

        mnStatistic.setText("Statistics");
        mnStatistic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnStatisticMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnStatistic);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbmiSortNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiSortNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbmiSortNameActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miExitActionPerformed

    private void dlgStatistic_tfComingBirthdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgStatistic_tfComingBirthdaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dlgStatistic_tfComingBirthdaysActionPerformed

    private void mnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAddMouseClicked
        // TODO add your handling code here:

        dlgAddEdit.pack();  // Without this the dialog window will be too small to see
        dlgAddEdit.setLocationRelativeTo(this);
        dlgAddEdit.setVisible(true);
        
        //UtilDateModel model = new UtilDateModel();
        //JDatePanelImpl datePanel = new JDatePanelImpl(model);
        //JDatePickerImpl datePicker = new JDatePickerImpl(datePanel);

        //frame.add(datePicker);

        
        
    }//GEN-LAST:event_mnAddMouseClicked

    private void mnStatisticMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnStatisticMouseClicked
        // TODO add your handling code here:
        dlgStatistic.pack();  // Without this the dialog window will be too small to see
        dlgStatistic.setLocationRelativeTo(this);
        dlgStatistic.setVisible(true);
        
    }//GEN-LAST:event_mnStatisticMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day07Birthdays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day07Birthdays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day07Birthdays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day07Birthdays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day07Birthdays().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dlgAddEdit;
    private javax.swing.JButton dlgAddEdit_btAddUpdate;
    private javax.swing.JButton dlgAddEdit_btCancel;
    private javax.swing.JTextField dlgAddEdit_tfName;
    private javax.swing.JDialog dlgStatistic;
    private javax.swing.JButton dlgStatistic_btDismiss;
    private javax.swing.JList<String> dlgStatistic_lstBirthday;
    private javax.swing.JTextField dlgStatistic_tfComingBirthdays;
    private javax.swing.JTextField dlgStatistic_tfTotalFriends;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JList<Birthday> lstBirthdays;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miExport;
    private javax.swing.JMenu mnAdd;
    private javax.swing.JMenu mnStatistic;
    private javax.swing.JRadioButtonMenuItem rbmiSortDaysTill;
    private javax.swing.JRadioButtonMenuItem rbmiSortName;
    private javax.swing.JRadioButtonMenuItem rbmiSoryDaysTill;
    // End of variables declaration//GEN-END:variables
}
