/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day01manyinputs;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author YingLuo
 */
public class Day01ManyInputs_Teacher extends javax.swing.JFrame {

    /**
     * Creates new form Day01ManyInputs
     */
    public Day01ManyInputs_Teacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblPets = new javax.swing.JLabel();
        lblContinent = new javax.swing.JLabel();
        rdbtBelow18 = new javax.swing.JRadioButton();
        rdbt18To35 = new javax.swing.JRadioButton();
        rdbt36Up = new javax.swing.JRadioButton();
        ckbCat = new javax.swing.JCheckBox();
        ckbDog = new javax.swing.JCheckBox();
        ckbOther = new javax.swing.JCheckBox();
        cmbContinent = new javax.swing.JComboBox<>();
        lblTemperature = new javax.swing.JLabel();
        slCTemperature = new javax.swing.JSlider();
        btRegister = new javax.swing.JButton();
        pnResult = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taResult = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Many Inputs");
        setResizable(false);

        lblName.setText("Name:");

        lblAge.setText("Age:");

        lblPets.setText("Pets:");

        lblContinent.setText("Continent of Residence:");

        buttonGroup1.add(rdbtBelow18);
        rdbtBelow18.setText("below 18");
        rdbtBelow18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtBelow18ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbt18To35);
        rdbt18To35.setText("18-35");

        buttonGroup1.add(rdbt36Up);
        rdbt36Up.setText("36 and Up");
        rdbt36Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbt36UpActionPerformed(evt);
            }
        });

        ckbCat.setText("cat");

        ckbDog.setText("dog");

        ckbOther.setText("other");

        cmbContinent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asia", "Africa", "North America", "South America", "Antarctica", "Europe", "Australia" }));

        lblTemperature.setText("Preferred Temperature[Celsius]:");

        slCTemperature.setMajorTickSpacing(5);
        slCTemperature.setMaximum(35);
        slCTemperature.setMinimum(15);
        slCTemperature.setMinorTickSpacing(1);
        slCTemperature.setPaintLabels(true);
        slCTemperature.setPaintTicks(true);
        slCTemperature.setSnapToTicks(true);

        btRegister.setText("Register Me");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        pnResult.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pnResultPropertyChange(evt);
            }
        });

        taResult.setColumns(20);
        taResult.setRows(5);
        jScrollPane1.setViewportView(taResult);

        javax.swing.GroupLayout pnResultLayout = new javax.swing.GroupLayout(pnResult);
        pnResult.setLayout(pnResultLayout);
        pnResultLayout.setHorizontalGroup(
            pnResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnResultLayout.setVerticalGroup(
            pnResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblContinent)
                                    .addComponent(lblPets)
                                    .addComponent(lblAge)
                                    .addComponent(lblName)
                                    .addComponent(lblTemperature))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmbContinent, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ckbCat)
                                                .addGap(82, 82, 82)
                                                .addComponent(ckbDog))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rdbtBelow18, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rdbt18To35)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(rdbt36Up))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ckbOther)
                                                .addGap(16, 16, 16))))
                                    .addComponent(slCTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(btRegister)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAge)
                        .addGap(29, 29, 29)
                        .addComponent(lblPets))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbtBelow18)
                            .addComponent(rdbt18To35)
                            .addComponent(rdbt36Up))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbCat)
                            .addComponent(ckbDog)
                            .addComponent(ckbOther))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContinent)
                    .addComponent(cmbContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slCTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTemperature))
                .addGap(38, 38, 38)
                .addComponent(btRegister)
                .addGap(27, 27, 27)
                .addComponent(pnResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbtBelow18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtBelow18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtBelow18ActionPerformed

    private void rdbt36UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbt36UpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbt36UpActionPerformed

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
        // TODO add your handling code here:
        
        String name = tfName.getText();
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(this, "Name must not be empty", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
        
        String age = "";
        if (rdbtBelow18.isSelected()){
            age = rdbtBelow18.getText();
        }else if (rdbt18To35.isSelected()){
            age = rdbt18To35.getText();
        }else if (rdbt36Up.isSelected()){
            age = rdbt36Up.getText();
        }else{
            JOptionPane.showMessageDialog(this, "Please choose your age range", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
        
        ArrayList<String> petList = new ArrayList<>();
        
        if(ckbCat.isSelected()){
            petList.add("Cat");
        }
        if(ckbDog.isSelected()){
            petList.add("Dog");
        }
        if(ckbOther.isSelected()){
            petList.add("Other");
        }
        
        String continent = cmbContinent.getSelectedItem().toString();
        
        int temperature = slCTemperature.getValue();
                                                                                                                       // USE STRING JOIN WITH COMA SEPERATOR
        String result = String.format("%nYour name: %s; age: %s; pets: %s; Continent: %s; Temperature: %d%n", name, age, String.join(", ", petList), continent, temperature);
        
        /* cannot catch up
        
        try (PrintWriter fileOutput = new PrintWriter(new FileWriter(new File("output.txt", true)))){
            
            fileOutput.write(result);
            
        }catch( IOException ex){
            
        }
        
        
        */
        
        if((rdbtBelow18.isSelected() || rdbt18To35.isSelected() || rdbt36Up.isSelected()) && (!name.isEmpty())){
            JOptionPane.showMessageDialog(this, result);
            // write the result into textarea within panel which could be set as invisible
            //pnResult.setVisible(true);
            //taResult.setText(result);
            
            // write the result into text output file
            writeOutputFile(result);
        }
    }//GEN-LAST:event_btRegisterActionPerformed

    private static File file = new File("output.txt");
    private static FileWriter fr = null;
    
    private static void writeOutputFile(String data){
        
        try{
            fr = new FileWriter(file, true);
            fr.write(data + "\r\n");
        }catch (IOException e){
            e.printStackTrace();
        }finally{
            try{
                fr.close();
            }catch (IOException e){
                e.printStackTrace();
            }
        }
    }
    
    private void pnResultPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pnResultPropertyChange
        // TODO add your handling code here:
        pnResult.setVisible(false);
    }//GEN-LAST:event_pnResultPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day01ManyInputs_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day01ManyInputs_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day01ManyInputs_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day01ManyInputs_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day01ManyInputs_Teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegister;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckbCat;
    private javax.swing.JCheckBox ckbDog;
    private javax.swing.JCheckBox ckbOther;
    private javax.swing.JComboBox<String> cmbContinent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblContinent;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPets;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JPanel pnResult;
    private javax.swing.JRadioButton rdbt18To35;
    private javax.swing.JRadioButton rdbt36Up;
    private javax.swing.JRadioButton rdbtBelow18;
    private javax.swing.JSlider slCTemperature;
    private javax.swing.JTextArea taResult;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
